--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzli/TradeEmpire
build-by-default: true
branches:
- stable
projects:
  TradeEmpire:
    path: ""
    libs:
    - src: ACM-PocketMine-MP/Commando/Commando
        version: ^3.2.1
        branch: PM5
...
